import colors from '@/styles/colors';
import {StyleSheet} from 'react-native';

export const storystyle = StyleSheet.create({
  storyParent: {
    marginRight: 10,
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
  },
  myStory: {
    backgroundColor: '#dfe6e9',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },

  imageBorder: {
    backgroundColor: '#bdc3c7',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: 70,
    height: 70,
    borderRadius: 50,
    margin: 3,
    borderWidth: 3,
    borderColor: 'white',
  },
  replyContainer: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    left: 10,
    padding: 12,
  },
  storyHeader: {
    flex: 1,
    flexDirection: 'row',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 20,
    marginBottom: 2,
  },
  userAvatar: {
    height: 30,
    width: 30,
    borderRadius: 15,
    backgroundColor: 'grey',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  centerAlign:{flexDirection: 'row', alignItems: 'center'},
  replyInput: {
    backgroundColor: 'transparent',
    borderColor: colors.white,
    borderWidth: 1,
    borderRadius: 20,
    padding: 10,
  },
  addIcon: {
    backgroundColor: '#0984e3',
    borderWidth: 3,
    borderColor: colors.white,
    padding: 2,
    borderRadius: 50,
    color: colors.white,
    justifyContent: 'center',
    fontSize: 18,
    position: 'absolute',
    zIndex: 100,
    bottom: 22,
    right: 2,
  },
  yourStoryText: {
    color: '#636e72',
    fontSize: 12,
    marginTop: 3,
  },
  storiesList: {
    paddingHorizontal: 15,
    paddingBottom: 15,
  },
});
